FROM ubuntu:php-fpm7.2-v2

RUN apt-get update

# pdo_oci.so
## oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/195000/oracle-instantclient19.5-basic-19.5.0.0.0-1.x86_64.rpm && \
  wget https://download.oracle.com/otn_software/linux/instantclient/195000/oracle-instantclient19.5-sqlplus-19.5.0.0.0-1.x86_64.rpm && \
  wget https://download.oracle.com/otn_software/linux/instantclient/195000/oracle-instantclient19.5-devel-19.5.0.0.0-1.x86_64.rpm && \
  apt-get install -y fakeroot alien libaio1 && \
  fakeroot alien --scripts *.rpm && dpkg -i *.deb && \
  apt-get remove -y alien && rm -fr oracle-instantclient19.5*

ENV ORACLE_HOME="/usr/lib/oracle/19.5/client64/"
ENV LD_LIBRARY_PATH="/usr/lib/oracle/19.5/client64/lib/:$LD_LIBRARY_PATH"

## OCI8
RUN /usr/local/php${PHP_VERSION}/bin/pecl download OCI8 && \
  tar xf oci8-2.2.0.tgz  && \
  cd oci8-2.2.0  && \
  /usr/local/php${PHP_VERSION}/bin/phpize  && \
  ./configure --with-oci8=instantclient,/usr/lib/oracle/19.5/client64/lib/ --with-php-config=/usr/local/php${PHP_VERSION}/bin/php-config  && \
  make install && \
  rm -fr oci8-2.2.0.tgz 

ENV PHP_VERSION 7.2.25
## pdo_oci.so
RUN tar xf php-${PHP_VERSION}.tar.xz && cd /php-${PHP_VERSION}/ext/pdo_oci/  && \
  /usr/local/php${PHP_VERSION}/bin/phpize  && \
  ./configure --with-php-config=/usr/local/php${PHP_VERSION}/bin/php-config  --with-pdo-oci=instantclient,/usr/lib/oracle/19.5/client64/lib/  && \
  make  && \
  make install && \
  rm -rf /php-${PHP_VERSION}

# memcache.so
RUN apt-get -y install git  libmemcached-dev  && \
  git clone https://github.com/php-memcached-dev/php-memcached.git  && \
  cd php-memcached  && \
  git checkout php7  && \
  /usr/local/php${PHP_VERSION}/bin/phpize  && \
  ./configure --with-php-config=/usr/local/php${PHP_VERSION}/bin/php-config  && \
  make  && \
  make install  && \
  cd .. && rm -rf php-memcached

# redis.so
RUN git clone https://github.com/phpredis/phpredis.git  && \
   cd phpredis  && \
  /usr/local/php${PHP_VERSION}/bin/phpize  && \
  ./configure --with-php-config=/usr/local/php${PHP_VERSION}/bin/php-config  && \
  make  && \
  make install  && \
  cd .. && rm -rf phpredis

# geoip.so
RUN apt-get install -y libgeoip-dev  && \
  /usr/local/php${PHP_VERSION}/bin/pecl install geoip-1.1.1.tgz  

# modudels
RUN echo  " \n\
extension_dir = $(/usr/local/php${PHP_VERSION}/bin/php-config --extension-dir)\n\
extension="redis.so"\n\
extension="pdo_oci.so"\n\
extension="oci8.so"\n\
extension="memcached.so"\n\
extension="geoip.so"\n\
" >> /usr/local/php${PHP_VERSION}/lib/php.ini

# clean
RUN cd / && \
  rm -rf  php-${PHP_VERSION} && \
  apt-get remove -y git && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# 上一层构建已经存在这个环境了
#WORKDIR /
#ENV PATH=$PATH:/
# CMD
CMD  ["start.sh"]


